### ISSUE TITLE
Reproducable crash when searching Brussel-Centraal - Brussel-Luxemburg

### ISSUE THREAD

**Issue by Fregf** [hyperrail/hyperrail-for-android#115]
Every time when searching Brussel-Centraal - Brussel-Luxemburg, HyperRail crashes with a StringIndexOutOfBoundsException and restarts to the HyperRail home screen instead of showing me all trains.

```
12-18 11:07:26.142 13619 13619 E AndroidRuntime: FATAL EXCEPTION: main
12-18 11:07:26.142 13619 13619 E AndroidRuntime: Process: be.hyperrail.android, PID: 13619
12-18 11:07:26.142 13619 13619 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=4; index=8
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at java.lang.String.substring(String.java:2027)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at c.a.a.c.c.v.<init>(IrailVehicleInfo.java:10)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at c.a.a.c.c.o.p(IrailApiParser.java:6)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at c.a.a.c.c.o.s(IrailApiParser.java:4)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at c.a.a.c.c.n.x(IrailApi.java:4)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at c.a.a.c.c.d.a(Unknown Source:6)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at com.android.volley.o.l.m(JsonRequest.java:4)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at com.android.volley.d$b.run(ExecutorDelivery.java:4)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-18 11:07:26.142 13619 13619 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Bertware** [comment]
I could not reproduce this one, possibly because it has been fixed already (I do remember seeing an error like that). You can try sideloading the latest build (https://github.com/hyperrail/hyperrail-for-android/releases/tag/v1.3.1) or wait for it to come to the beta release track,

**Comment by Fregf** [comment]
It's working now indeed.
